nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.0.cjs

npmPublishRegistry: "https://registry.npmjs.org"
npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: ${NPM_AUTH_TOKEN:-}
