nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: "${NPM_AUTH_TOKEN:-}"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
